[project]
name = "langchain-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.0",
    "langchain-core>=0.3.76",
    "langchain-deepseek>=0.1.4",
    "langgraph>=0.2.27",
]
